<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QFlot
Examples::AddPluginExampleFile('QFlot', 'example/qflot-bar.php QFlot: Display a bar chart');
Examples::AddPluginExampleFile('QFlot', 'example/qflot-timeseries.php QFlot: Display a time series chart');
//// END QFlot

//// BEGIN QAutoCompleteTextBox
Examples::AddPluginExampleFile('QAutoCompleteTextBox', 'example/autocomplete.php * Auto-complete Textbox Example');
//// END QAutoCompleteTextBox

//// BEGIN QSelect2ListBox
Examples::AddPluginExampleFile('QSelect2ListBox', 'example/select2listbox.php QSelect2ListBox: QSelect2ListBox: selector control based on select2 JQuery plugin');
//// END QSelect2ListBox

?>
