<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QFlot
QApplicationBase::$ClassFile['qflot'] = __PLUGINS__ . '/QFlot/includes/QFlot.class.php';
QApplicationBase::$ClassFile['qflotseries'] = __PLUGINS__ . '/QFlot/includes/QFlotSeries.class.php';
//// END QFlot

//// BEGIN QAutoCompleteTextBox
QApplicationBase::$ClassFile['qautocompletetextboxbase'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QAutoCompleteTextBoxBase.class.php';
QApplicationBase::$ClassFile['qajaxautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QAjaxAutoCompleteTextBox.class.php';
QApplicationBase::$ClassFile['qjavascriptautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QJavaScriptAutoCompleteTextBox.class.php';
//// END QAutoCompleteTextBox

//// BEGIN QSelect2ListBox
QApplicationBase::$ClassFile['qselect2listbox'] = __PLUGINS__ . '/QSelect2ListBox/includes/QSelect2ListBox.class.php';
QApplicationBase::$ClassFile['qselect2listboxbase'] = __PLUGINS__ . '/QSelect2ListBox/includes/QSelect2ListBoxBase.class.php';
QApplicationBase::$ClassFile['qselect2listboxgen'] = __PLUGINS__ . '/QSelect2ListBox/includes/QSelect2ListBoxGen.class.php';
//// END QSelect2ListBox

?>